### ISSUE TITLE
channel vs group

### ISSUE THREAD

**Issue by facmasterII** [DamianMorozov/TgDownloader#14]
Hello bro. Thanks for your work. Is great. But 1 only problem. For channel donwload good. But group dont donwload any.
It doesn't recognize the messages I think.

**Comment by DamianMorozov** [comment]
How exactly do you use TgDownloader for groups? Can you give access to a public group for a test?

**Comment by DamianMorozov** [comment]
# Guide to download groups

1. Join a group on Telegram.
2. Right click any message -> Copy Message Link.
3. Edit the link on the clipboard `https://t.me/c/group_id/message_number` like this `group_id`.
4. Run `TgDownloaderConsole.exe` (Windows) or `dotnet TgDownloaderConsole.dll` (Linux).
5. Go to the -> `Download settings` -> `Setup source (ID/username)` -> paste `group_id`.
6. Go to the -> `Setup download folder` -> `Drive:\Storage_path`.
7. Go to the -> `Manual download`.
8. Enjoy.

**Comment by DamianMorozov** [comment]
Added your problem to my local task tracker.

**Comment by DamianMorozov** [comment]
Solve that problem in last release [v0.2.230](https://github.com/DamianMorozov/TgDownloader/releases/tag/v0.2.230).
