### ISSUE TITLE
Is it possible to download from a bot chat?

### ISSUE THREAD

**Issue by adocampo** [DamianMorozov/TgDownloader#15]
Hello, 

I was wondering if it would be possible to download media from a bot chat. Let me explain.
I have a bot called, for example, tgdownloader_bot, so any media I see I want to download, I forward to that bot.
I've tried to use the chat_id of that bot, and forward a media from another channel, but it doesn't do anything.

Is even possible?
Thank you!

**Comment by DamianMorozov** [comment]
I think it's possible. I'll have to check it out.

**Comment by DamianMorozov** [comment]
You are right. The bot has other ways to connect. There is no such support yet.
