### ISSUE TITLE
more details pls

### ISSUE THREAD

**Issue by kklod** [DamianMorozov/TgDownloader#16]
wanna see the current task imformation, such as filename, speed, filesize ...   and, U really did a good job!  thanks

**Comment by DamianMorozov** [comment]
Thanks for the review.
Could you describe in more detail what information you would like to see about the downloaded files?
Where would you like to see this information displayed? In the local storage or in the program interface?

**Comment by DamianMorozov** [comment]
Tell me more about what information you want to see?
![image](https://github.com/user-attachments/assets/8c3d48f5-d67c-4065-b6c3-fede4bedce71)
