### ISSUE TITLE
Containerize your application using Docker

### ISSUE THREAD

**Issue by DRMPN** [DamianMorozov/TgDownloader#20]
It would be great if you could package this application in a docker.

**Comment by DamianMorozov** [comment]
Could you give me an example of an implementation? I am just starting to learn docker.

**Comment by DRMPN** [comment]
Unfortunately, I'm no C# developer and cannot recommend examples, but you can google some.
1) install Docker
2) in your project directory create dockerfile
3) fill in required information to create image
4) create docker.compose to set up volumes to persist some data and etc
5) try to use your app yourself and make corrections
6) done, write an instruction how to set it up

**Comment by frezeen** [comment]
i do a docker container for this soft, if someone need it

https://hub.docker.com/r/frezeen/tgdownloader

**Comment by DamianMorozov** [comment]
Thank you so much for this docker image. I will put a link to it in our group for discussion.

**Comment by DamianMorozov** [comment]
Hello everyone. I suggest to take part in testing of docker-version.
https://hub.docker.com/r/damianmorozov/tgdownloaderconsole
