### ISSUE TITLE
how to Download only the type of file i want?

### ISSUE THREAD

**Issue by ninoxscutulata** [DamianMorozov/TgDownloader#26]
Can we set the file format? For example, I want to download only pdf among documents.

**Comment by DamianMorozov** [comment]
I will be adding a "customize filters" option soon.

**Comment by DamianMorozov** [comment]
Check this version: [TgDownloader v0.1.700 Preview](https://github.com/DamianMorozov/TgDownloader/releases/tag/v0.1.700).
