### ISSUE TITLE
Does it work in private chats?

### ISSUE THREAD

**Issue by axel845845** [DamianMorozov/TgDownloader#3]
Trying to download from chats or private groups does not work.

**Comment by DamianMorozov** [comment]
Telegram does not allow access to private chats. You can only download files from groups or channels you are a member of.

**Comment by DamianMorozov** [comment]
Tested the work with a private group. It works, but there are conditions:
- you must be a member of that group;
- the group administrator has allowed you to download files.

**Comment by DamianMorozov** [comment]
It looks like a closed question.
