### ISSUE TITLE
General questions.

### ISSUE THREAD

**Issue by ShiroUwUs7** [DamianMorozov/TgDownloader#31]
for First/Last ID it shows 2/xxxx will that change once its done to avoid double downloading? 
if i ctrl+c (hot key to cancel any operation in terminal) will the progress be saved (except the one its currently downloading so if it got down downloading 1500 files and is on 1501 would it pick up from 1501 (redownloading that file obviouslly) and then continue on forward to the last message? is that how it works normally if auto update is on also? I didnt see anything about it in the guides on how it functions.  
![vS0lrjb 1](https://user-images.githubusercontent.com/53096166/229928996-fcfb1b9c-dc25-4401-85a6-aa4f88ec654e.png)

Edit: Went ahead and closed the program and re-opened it: I had to grab the message id manually and set it manually as auto kept moving it back to 2 out of 6000+.
Whenever I re start the program it makes me enter in the hash id & phone number along with the group id as well. isn't it already saved when pressing "save settings"
one last question is about the filters, for multi extention: trying to exclude mp4/videos from being downloaded for a video channel that share videos. as its the same video being forwarded from another video channel that im already downloading. but cant figure out the filters or how to set them to only download images on one channel and videos and images on the other. 
images = .jpg and vides = .mp4

**Comment by DamianMorozov** [comment]
Thank you for your questions.
Check here: [Guide for filters settings](https://github.com/DamianMorozov/TgDownloader/blob/preview/GUIDES.md)

**Comment by DamianMorozov** [comment]
Update for new version.
Fixed store First ID. Wait a little.

**Comment by DamianMorozov** [comment]
Can you show me an example of a channel what you mean?
Where should this option be displayed?

**Comment by jaimedelano** [comment]
Every video, image, or file uploaded to Telegram can have a optional text description.
Can you add an option to save it?

**Comment by jaimedelano** [comment]
I could not find any reference to description or text at TgDownloader/Core/TgDownloader/Helpers/TgClientHelper.cs ...

**Comment by DamianMorozov** [comment]
Unfortunately, this is one of the open questions - there is no documentation:
- User's Guide;
- Administrator's Guide;
- Developer's Guide.
