### ISSUE TITLE
Where to find TgDownloader v1.2.333.zip?

### ISSUE THREAD

**Issue by AboRamy** [DamianMorozov/TgDownloader#32]
Is the file **TgDownloader v1.2.333.zip** deleted? where can I find it?

Thanks

**Comment by DamianMorozov** [comment]
All release are [here](https://github.com/DamianMorozov/TgDownloader/releases)
Last preview release [v0.1.720 Preview](https://github.com/DamianMorozov/TgDownloader/releases/tag/v0.1.720)
