### ISSUE TITLE
info of date range

### ISSUE THREAD

**Issue by lollos73** [DamianMorozov/TgDownloader#35]
hi
i'm new in this program and i like it
only a question is possible to set a range of date for download messages? some group are on from 2020 and have 20-30.000 messages.... for Terabyte ... can i for esample download last month (1-2-3 or more) or year?
ty dor response

**Comment by DamianMorozov** [comment]
One option that might help is the `Start message ID'.

**Comment by lollos73** [comment]
ty boss i think i have do somethng wrong
![image](https://github.com/DamianMorozov/TgDownloader/assets/29383778/4196e5a2-59da-4d89-8011-0b9e53607f57)
i have to stop this?

**Comment by DamianMorozov** [comment]
To stop the command process press `Ctrl + C`.
After restart app, setup thies option `Start message ID`.

**Comment by lollos73** [comment]
ok solved ty and now last question (program running w8 for end of task) start is ok and end/last? can be set? explain, if i set the id for range 01/05 - today , is possible to set for example april to may only? or i have to redownload april+may to today?
sorry for stupid question this is my first time on this program.

**Comment by lollos73** [comment]
here again .... sorry ok for first message, but last?
i want to download month for mont ie giune july etc i pick id from 1st day, but always download all to the end... 
the 2 rewrite are false...
