### ISSUE TITLE
auto update doesnt appear to download new media

### ISSUE THREAD

**Issue by nak0604** [DamianMorozov/TgDownloader#39]
So, I have ran auto update several times while media gets posted in a chat. I have noticed that auto update doesnt  always download media in the chat, compared to details in the file explorer. I had one group chat with friends on vacation and I had just ran the auto download but when I looked in the file explorer some stuff was missing. I grabbed the source for the chat and pasted it in to manually download anything new and it was  3000 messages behind.

**Comment by DikkeMoeders0** [comment]
Hey man, try unmuting the channel.
Let me know if that worked for you 👍

**Comment by DikkeMoeders0** [comment]
and btw you need to have all the messages as read btw

**Comment by DamianMorozov** [comment]
Open the official Telegram Client. Go to the channel -> go to the last messages.
After that, run the TgDownloader again -> go to the source -> run download.
