### ISSUE TITLE
TgDownloader Console error reading the ID

### ISSUE THREAD

**Issue by ryangar888** [DamianMorozov/TgDownloader#42]
Hi team,
I tried latest version of Tg Downloader Console and the application can not load message in channel. This only show Test
![image](https://github.com/DamianMorozov/TgDownloader/assets/124960502/3be417bd-e888-4620-a828-68c9d6542661)

**Comment by DamianMorozov** [comment]
You're right. The latest version has a TgDownloaderConsole error reading the ID of the last message.
Will fix this error in the near future.

**Comment by DamianMorozov** [comment]
Check new update [v0.2.540](https://github.com/DamianMorozov/TgDownloader/releases/tag/v0.2.540).
That should solve your problem.

**Comment by DamianMorozov** [comment]
Did it help with your problem?
