### ISSUE TITLE
Last ID stuck at 1 and Filter Count stuck at 0

### ISSUE THREAD

**Issue by mar55audit** [DamianMorozov/TgDownloader#45]
OS - Windows 11
Version - Latest version v0.2.550 of TgDownloaderConsole-AnyCPU.zip
Extracted the zip file, Launch Console (under Admin privileges) and Run the TgDownloaderConsole.exe command
Create New Storage, entered API Hash, APP ID, Mobile number, Verification code and Password
Main Menu shows up
But under Filters, All filters count is 0
Then under Download, after putting Source and Download location, first/last ID still shows 1/1
Then Manual Download does nothing
<img width="558" alt="tgdownloader" src="https://github.com/DamianMorozov/TgDownloader/assets/150347856/a8f50e4c-2c61-4445-840c-3e7848b1211f">

Everything works fine in v0.2.300 because Filter count shows as 1 by default

**Comment by DamianMorozov** [comment]
Check new release [v0.2.570](https://github.com/DamianMorozov/TgDownloader/releases/tag/v0.2.570).
