### ISSUE TITLE
cant connect to tg server

### ISSUE THREAD

**Issue by frezeen** [DamianMorozov/TgDownloader#46]
Operating system:
windows 11 pro

TgDownloaderConsole / TgDownloaderDesktop version:
desktop version 0.2.570 has issue. console version work

Test-case steps
unzip .zip, launch .exe , insert hash, insert app id, insert phone number. no code from telegram

Screenshots
none

note: same as https://github.com/DamianMorozov/TgDownloader/discussions/40

solution is to create .db and .session with console version and paste them in desktop version for to bypass this session creation issue

**Comment by DamianMorozov** [comment]
Please, use the [issue template](https://github.com/DamianMorozov/TgDownloader/blob/main/ISSUE.md).

**Comment by DamianMorozov** [comment]
Did you press the "Connect the client to TG server" button after entering the fields?
