### ISSUE TITLE
On groups with channels it doesn't download all of the content

### ISSUE THREAD

**Issue by TooShyTo** [DamianMorozov/TgDownloader#51]
As I wrote it skips some or most of the content :[

**Comment by DamianMorozov** [comment]
Please, use [Issue template](https://github.com/DamianMorozov/TgDownloader/blob/main/ISSUE.md).

**Comment by DamianMorozov** [comment]
This may be due to unsupported characters for file names. This fix will be included in the next release.

**Comment by DamianMorozov** [comment]
Try to use the [v0.5.180 Release](https://github.com/DamianMorozov/TgDownloader/releases/tag/v0.5.180).
