### ISSUE TITLE
Only VIDEOS

### ISSUE THREAD

**Issue by denny4-user** [DamianMorozov/TgDownloader#54]
I use the Download Telegram Console  what parameter do I need to enter so that I can download - ONLY videos?

**Comment by DamianMorozov** [comment]
![image](https://github.com/DamianMorozov/TgDownloader/assets/13628284/b852da7c-2843-4c1c-b26d-2a79be6ccdb8)
![image](https://github.com/DamianMorozov/TgDownloader/assets/13628284/da4ee272-b722-4f03-9c05-2a1603794073)
Try to add multi extension filter: Videos | *.mkv, *.mp4
