### ISSUE TITLE
How to automatically download new posts?

### ISSUE THREAD

**Issue by EEB9** [DamianMorozov/TgDownloader#59]
How can I use this to automatically download new posts in a public telegram channel?

**Comment by Tusharvoid** [comment]
try to re run the program it will automatically update its backend file and re download it

**Comment by Tusharvoid** [comment]
you can check my script which is working and download files   @DamianMorozov  can i work on this project

**Comment by DamianMorozov** [comment]
Hello. What's the script?

**Comment by Tusharvoid** [comment]
https://github.com/Tusharvoid/telegram_media_downloader my bad sorry to say it as script but this repo  you can use it 
no error working fine
