### ISSUE TITLE
Console return error SQL Error 1: no such table __EFMigrationsHistory

### ISSUE THREAD

**Issue by mbarreradev** [DamianMorozov/TgDownloader#60]
Hello, I tried using the latest version 0.5.170 (TgDownloaderConsole-AnyCPU version), it doesn't work, it returns the following error:

![image](https://github.com/user-attachments/assets/6528aaf8-7803-4f5b-bb72-c7371a42e348)

Thank you

**Comment by DamianMorozov** [comment]
You're right. Expect a correction.

**Comment by DamianMorozov** [comment]
Try to use v0.5.180
![image](https://github.com/user-attachments/assets/d4977745-1f8d-49aa-a305-7d6e2e3b15bb)

**Comment by mbarreradev** [comment]
Hello, I tested the new version and it works without any issues, thank you
