### ISSUE TITLE
latest version does not show the configurations

### ISSUE THREAD

**Issue by TheDoom95** [DamianMorozov/TgDownloader#62]
It does not show the configurations in the latest version.  in desktop mode

![image](https://github.com/user-attachments/assets/422a67dd-a67f-4d76-9c38-17ecb2b5a218)

**Comment by DamianMorozov** [comment]
You're right. Expect the functionality to be migrated.

**Comment by DamianMorozov** [comment]
Use this version: [v0.5.230 Release](https://github.com/DamianMorozov/TgDownloader/releases/tag/v0.5.230).
See this [screenshots](https://github.com/DamianMorozov/TgDownloader/blob/main/Docs/SCREENSHOTS.md).
